2023-11-29 00:28:06 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:28:06 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:28:06 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:06 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'migrations' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'migrations' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:28:56 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:28:56 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:28:56 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:30:11 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:30:11 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:30:11 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:32:03 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:03 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:03 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:03 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'migrations' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'migrations' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:32:27 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:27 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:27 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'testimonial_usage' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:32:32 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:32 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:32 error: uncaughtException: ER_BAD_FIELD_ERROR: Unknown column 'update_at' in 'testimonial_usage'
QueryFailedError: ER_BAD_FIELD_ERROR: Unknown column 'update_at' in 'testimonial_usage'
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:32:42 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialUsageService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:42 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:43 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:43 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:32:43 error: uncaughtException: ER_TABLE_EXISTS_ERROR: Table 'customer' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'customer' already exists
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
2023-11-29 00:33:36 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:33:36 error: uncaughtException: Pool is closed.
Error: Pool is closed.
    at /Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:149:17
    at Array.forEach (<anonymous>)
    at Pool.releaseConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:148:37)
    at Pool._removeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:277:8)
    at Pool._purgeConnection (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:258:8)
    at Pool.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Pool.js:182:10)
    at /Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:463:27
    at new Promise (<anonymous>)
    at MysqlDriver.disconnect (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlDriver.ts:462:20)
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:304:27)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CustomerService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at UserService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: Cannot execute operation on "default" connection because connection is not yet established.
CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
    at DataSource.destroy (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:302:19)
    at DataSource.initialize (/Users/fernandolba/development/my-commerce/back/src/data-source/DataSource.ts:277:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestimonialService.initRepository (/Users/fernandolba/development/my-commerce/back/src/config/base.service.ts:27:24)
2023-11-29 00:33:36 error: uncaughtException: ER_DUP_KEY: Can't write; duplicate key in table '#sql-1_12'
QueryFailedError: ER_DUP_KEY: Can't write; duplicate key in table '#sql-1_12'
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/fernandolba/development/my-commerce/back/node_modules/mysql/lib/Connection.js:88:28)
